services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_php
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 5s
      retries: 5
      
  nginx:
    container_name: api_nginx
    image: nginx:latest
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
