FROM php:8.3-fpm 

RUN apt-get update && apt-get install -y \ 
    git \ 
    unzip \ 
    libzip-dev \ 
    libpng-dev \ 
    libjpeg-dev \ 
    && docker-php-ext-install pdo_mysql mysqli gd zip 

# Instalar PhpRedis
RUN pecl install redis \
    && docker-php-ext-enable redis


WORKDIR /var/www/html

RUN curl -sS https://getcomposer.org/installer | php -- \ 
    --install-dir=/usr/bin --filename=composer 

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

RUN sed -i 's/\r$//' /usr/local/bin/docker-entrypoint.sh \
    && chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

CMD ["php-fpm"]