FROM php:8.3-fpm 

RUN apt-get update && apt-get install -y \ 
    git \ 
    unzip \ 
    libzip-dev \ 
    libpng-dev \ 
    libjpeg-dev \ 
    && docker-php-ext-install pdo_mysql mysqli gd zip 

WORKDIR /var/www/html


RUN curl -sS https://getcomposer.org/installer | php -- \ 
    --install-dir=/usr/bin --filename=composer 

# RUN chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache 

# Copia apenas o entrypoint
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Configura o entrypoint

EXPOSE ${PORT:-80} ${PROD_PORT:-443} 9000 

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["php-fpm"]