
FROM php:8.3-fpm


WORKDIR /var/www/html


RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    && docker-php-ext-install pdo_mysql mysqli gd zip

COPY ./app .

RUN chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache

EXPOSE ${PORT:-80} ${PROD_PORT:-443} 9000


CMD ["php-fpm"]