[supervisord]
nodaemon=true

[program:laravel-scheduler]
command=php /var/www/html/artisan schedule:work
autostart=true
autorestart=true
stdout_logfile=/var/log/scheduler.log
stderr_logfile=/var/log/scheduler.log

[program:laravel-worker-email-verification]
command=php /var/www/html/artisan queue:work --queue=email-verification --sleep=3 --tries=3
autostart=true
autorestart=true
stdout_logfile=/var/log/queue-email-verification.log
stderr_logfile=/var/log/queue-email-verification.log

[program:laravel-worker-forgot-password]
command=php /var/www/html/artisan queue:work --queue=forgot-password --sleep=3 --tries=3
autostart=true
autorestart=true
stdout_logfile=/var/log/queue-forgot-password.log
stderr_logfile=/var/log/queue-forgot-password.log

[program:laravel-worker-two-factor]
command=php /var/www/html/artisan queue:work --queue=two-factor --sleep=3 --tries=3
autostart=true
autorestart=true
stdout_logfile=/var/log/queue-two-factor.log
stderr_logfile=/var/log/queue-two-factor.log

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.log
stderr_logfile=/var/log/php-fpm.log