    [supervisord]
    nodaemon=true

    [program:laravel-scheduler]
    command=php /var/www/html/artisan schedule:work
    autostart=true
    autorestart=true
    stdout_logfile=/var/www/html/storage/logs/scheduler.log
    stderr_logfile=/var/www/html/storage/logs/scheduler.log
    user=www-data

    [program:laravel-worker-email-verification]
    command=php /var/www/html/artisan queue:work --queue=email-verification --sleep=3 --tries=3 --timeout=60
    autostart=true
    autorestart=true
    stdout_logfile=/var/www/html/storage/logs/queue-email-verification.log
    stderr_logfile=/var/www/html/storage/logs/queue-email-verification.log
    user=www-data

    [program:laravel-worker-forgot-password]
    command=php /var/www/html/artisan queue:work --queue=forgot-password --sleep=3 --tries=3 --timeout=60
    autostart=true
    autorestart=true
    stdout_logfile=/var/www/html/storage/logs/queue-forgot-password.log
    stderr_logfile=/var/www/html/storage/logs/queue-forgot-password.log
    user=www-data

    [program:laravel-worker-two-factor]
    command=php /var/www/html/artisan queue:work --queue=two-factor --sleep=3 --tries=3 --timeout=60
    autostart=true
    autorestart=true
    stdout_logfile=/var/www/html/storage/logs/queue-two-factor.log
    stderr_logfile=/var/www/html/storage/logs/queue-two-factor.log
    user=www-data